### ISSUE TITLE
blocTest

### ISSUE THREAD

**Issue by kbudulski** [Welltested-AI/welltested#6]
Hi 👋 Very cool library, I'm wondering if there will be a possibility to generate [bloc_test ](https://pub.dev/packages/bloc_test) (maybe even with [mocktail](https://pub.dev/packages/mocktail))?

And also did you consider adding `dart fix --apply` command after generating the files? It cleans it all up pretty nicely 🙂

**Comment by samyakkkk** [comment]
Hi @kbudulski 👋 thanks so much! 

Since welltested is self-learning, if you can update one of the generated unit tests to use bloc_test and mocktail, and save it using `welltested save unit`, the next tests will automatically start using it. 

Many of our users do generate bloc_test with mocktail tests using welltested this way.

Also thanks for the dart fix suggestion, we will discuss it and include it in our roadmap!
